[lakus]
title = "LAKUS"
url = "https://www.lakus.live/ko/"
entrySelector = "div.swiper-wrapper div.swiper-slide"
titleSelector = "div[class^='HomeSwiper__Title']"
linkSelector = "a[class^='HomeSwiper__InfoInner']"
contentSelector = "div[class^='HomeSwiper__StartDate']"
imageSelector = "img.h-full"
waitForSelector = "div.swiper-wrapper div.swiper-slide"
